set(CMAKE_BUILD_TYPE DEBUG) 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++2a")
#add_definitions(-D__cplusplus=201103L)  
add_definitions(-DICE_CPP11_MAPPING)  
set(CMAKE_INSTALL_PREFIX  ${CMAKE_CURRENT_SOURCE_DIR}/source/Deploy)


if(DEFINED ENV{ICE_HOME})
	include_directories($ENV{ICE_HOME}/include)
endif()
if(DEFINED ENV{BOOST_HOME})
	include_directories($ENV{BOOST_HOME}/include)
endif()
if(DEFINED ENV{HI_REDIS})
	include_directories($ENV{HI_REDIS}/include/hiredis)
	link_directories($ENV{HI_REDIS}/lib)
endif()