// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: devicestatus/devicestatus.proto

package devicestatus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOW  Status = 0
	Status_STATUS_ONLINE  Status = 1
	Status_STATUS_OFFLINE Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOW",
		1: "STATUS_ONLINE",
		2: "STATUS_OFFLINE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOW":  0,
		"STATUS_ONLINE":  1,
		"STATUS_OFFLINE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_devicestatus_devicestatus_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_devicestatus_devicestatus_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{0}
}

type Code int32

const (
	Code_CODE_UNKNOW            Code = 0
	Code_CODE_SUCCESS           Code = 1
	Code_CODE_FAIL              Code = 2
	Code_CODE_DEVICEID_INVALAID Code = 3
	Code_CODE_STATUS_INVALAID   Code = 4
	Code_CODE_ACCESSID_INVALAID Code = 5
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_UNKNOW",
		1: "CODE_SUCCESS",
		2: "CODE_FAIL",
		3: "CODE_DEVICEID_INVALAID",
		4: "CODE_STATUS_INVALAID",
		5: "CODE_ACCESSID_INVALAID",
	}
	Code_value = map[string]int32{
		"CODE_UNKNOW":            0,
		"CODE_SUCCESS":           1,
		"CODE_FAIL":              2,
		"CODE_DEVICEID_INVALAID": 3,
		"CODE_STATUS_INVALAID":   4,
		"CODE_ACCESSID_INVALAID": 5,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_devicestatus_devicestatus_proto_enumTypes[1].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_devicestatus_devicestatus_proto_enumTypes[1]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{1}
}

type GetHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHostReq) Reset() {
	*x = GetHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostReq) ProtoMessage() {}

func (x *GetHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostReq.ProtoReflect.Descriptor instead.
func (*GetHostReq) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{0}
}

type GetHostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *GetHostResp) Reset() {
	*x = GetHostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostResp) ProtoMessage() {}

func (x *GetHostResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostResp.ProtoReflect.Descriptor instead.
func (*GetHostResp) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{1}
}

func (x *GetHostResp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *GetStatusReq) Reset() {
	*x = GetStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusReq) ProtoMessage() {}

func (x *GetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusReq.ProtoReflect.Descriptor instead.
func (*GetStatusReq) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   Status `protobuf:"varint,1,opt,name=status,proto3,enum=devicestatus.Status" json:"status,omitempty"`
	AccessId int32  `protobuf:"varint,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	Code     Code   `protobuf:"varint,3,opt,name=code,proto3,enum=devicestatus.Code" json:"code,omitempty"`
}

func (x *GetStatusResp) Reset() {
	*x = GetStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResp) ProtoMessage() {}

func (x *GetStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResp.ProtoReflect.Descriptor instead.
func (*GetStatusResp) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResp) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOW
}

func (x *GetStatusResp) GetAccessId() int32 {
	if x != nil {
		return x.AccessId
	}
	return 0
}

func (x *GetStatusResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNKNOW
}

type SetStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status   Status `protobuf:"varint,2,opt,name=status,proto3,enum=devicestatus.Status" json:"status,omitempty"`
	AccessId int32  `protobuf:"varint,3,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
}

func (x *SetStatusReq) Reset() {
	*x = SetStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusReq) ProtoMessage() {}

func (x *SetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusReq.ProtoReflect.Descriptor instead.
func (*SetStatusReq) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{4}
}

func (x *SetStatusReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetStatusReq) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOW
}

func (x *SetStatusReq) GetAccessId() int32 {
	if x != nil {
		return x.AccessId
	}
	return 0
}

type SetStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code `protobuf:"varint,1,opt,name=code,proto3,enum=devicestatus.Code" json:"code,omitempty"`
}

func (x *SetStatusResp) Reset() {
	*x = SetStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicestatus_devicestatus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResp) ProtoMessage() {}

func (x *SetStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicestatus_devicestatus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResp.ProtoReflect.Descriptor instead.
func (*SetStatusResp) Descriptor() ([]byte, []int) {
	return file_devicestatus_devicestatus_proto_rawDescGZIP(), []int{5}
}

func (x *SetStatusResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNKNOW
}

var File_devicestatus_devicestatus_proto protoreflect.FileDescriptor

var file_devicestatus_devicestatus_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x21, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x22, 0x2b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x82, 0x01,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x76, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x2a, 0x42, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x46,
	0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x2a, 0x8a, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43,
	0x45, 0x49, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x41, 0x49, 0x44, 0x10, 0x03, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x41, 0x49, 0x44, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x49, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x41,
	0x49, 0x44, 0x10, 0x05, 0x32, 0xe1, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x18, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x72, 0x74, 0x69, 0x6f,
	0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_devicestatus_devicestatus_proto_rawDescOnce sync.Once
	file_devicestatus_devicestatus_proto_rawDescData = file_devicestatus_devicestatus_proto_rawDesc
)

func file_devicestatus_devicestatus_proto_rawDescGZIP() []byte {
	file_devicestatus_devicestatus_proto_rawDescOnce.Do(func() {
		file_devicestatus_devicestatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_devicestatus_devicestatus_proto_rawDescData)
	})
	return file_devicestatus_devicestatus_proto_rawDescData
}

var file_devicestatus_devicestatus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_devicestatus_devicestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_devicestatus_devicestatus_proto_goTypes = []interface{}{
	(Status)(0),           // 0: devicestatus.Status
	(Code)(0),             // 1: devicestatus.Code
	(*GetHostReq)(nil),    // 2: devicestatus.GetHostReq
	(*GetHostResp)(nil),   // 3: devicestatus.GetHostResp
	(*GetStatusReq)(nil),  // 4: devicestatus.GetStatusReq
	(*GetStatusResp)(nil), // 5: devicestatus.GetStatusResp
	(*SetStatusReq)(nil),  // 6: devicestatus.SetStatusReq
	(*SetStatusResp)(nil), // 7: devicestatus.SetStatusResp
}
var file_devicestatus_devicestatus_proto_depIdxs = []int32{
	0, // 0: devicestatus.GetStatusResp.status:type_name -> devicestatus.Status
	1, // 1: devicestatus.GetStatusResp.code:type_name -> devicestatus.Code
	0, // 2: devicestatus.SetStatusReq.status:type_name -> devicestatus.Status
	1, // 3: devicestatus.SetStatusResp.code:type_name -> devicestatus.Code
	2, // 4: devicestatus.StatusService.GetHost:input_type -> devicestatus.GetHostReq
	4, // 5: devicestatus.StatusService.GetStatus:input_type -> devicestatus.GetStatusReq
	6, // 6: devicestatus.StatusService.SetStatus:input_type -> devicestatus.SetStatusReq
	3, // 7: devicestatus.StatusService.GetHost:output_type -> devicestatus.GetHostResp
	5, // 8: devicestatus.StatusService.GetStatus:output_type -> devicestatus.GetStatusResp
	7, // 9: devicestatus.StatusService.SetStatus:output_type -> devicestatus.SetStatusResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_devicestatus_devicestatus_proto_init() }
func file_devicestatus_devicestatus_proto_init() {
	if File_devicestatus_devicestatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_devicestatus_devicestatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicestatus_devicestatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicestatus_devicestatus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicestatus_devicestatus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicestatus_devicestatus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicestatus_devicestatus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_devicestatus_devicestatus_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devicestatus_devicestatus_proto_goTypes,
		DependencyIndexes: file_devicestatus_devicestatus_proto_depIdxs,
		EnumInfos:         file_devicestatus_devicestatus_proto_enumTypes,
		MessageInfos:      file_devicestatus_devicestatus_proto_msgTypes,
	}.Build()
	File_devicestatus_devicestatus_proto = out.File
	file_devicestatus_devicestatus_proto_rawDesc = nil
	file_devicestatus_devicestatus_proto_goTypes = nil
	file_devicestatus_devicestatus_proto_depIdxs = nil
}
